# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Unspecified')], max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('newsletter', models.BooleanField(default=False, help_text='Subscribed to email list')),
                ('magazine', models.BooleanField(default=False, help_text='Receives print magazine')),
                ('promotions', models.BooleanField(default=False, help_text='Opted into receiving promotions')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
