# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='magazine',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='newsletter',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='promotions',
        ),
    ]
