# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=5)),
                ('product_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
