# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-23 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postText',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
