# Generated by Django 2.0.1 on 2018-01-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180112_0042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Catalog',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='question_text',
            new_name='title',
        ),
    ]
